--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/11/2021 10:05:58 PM
-- Server version: 10.5.9
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS chatbot;

CREATE DATABASE chatbot
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

--
-- Set default database
--
USE chatbot;

--
-- Create table `storysteps`
--
CREATE TABLE storysteps (
  id int(11) NOT NULL AUTO_INCREMENT,
  story_id int(11) NOT NULL,
  intent_id int(11) NOT NULL,
  utter_id int(11) NOT NULL,
  `index` int(11) NOT NULL,
  created_at datetime DEFAULT NULL,
  update_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6001,
AVG_ROW_LENGTH = 61,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create table `stories`
--
CREATE TABLE stories (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(255) NOT NULL,
  story_uuid char(36) NOT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6001,
AVG_ROW_LENGTH = 116,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create table `utterresponses`
--
CREATE TABLE utterresponses (
  id int(11) NOT NULL AUTO_INCREMENT,
  content text NOT NULL,
  utter_id int(11) NOT NULL,
  type varchar(255) NOT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6103,
AVG_ROW_LENGTH = 97,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create table `utters`
--
CREATE TABLE utters (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(255) NOT NULL,
  utter_uuid char(36) NOT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6032,
AVG_ROW_LENGTH = 106,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create table `examples`
--
CREATE TABLE examples (
  id int(11) NOT NULL AUTO_INCREMENT,
  content text DEFAULT NULL,
  intent_id int(11) DEFAULT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6032,
AVG_ROW_LENGTH = 110,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create table `intents`
--
CREATE TABLE intents (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(255) NOT NULL,
  intent_uuid char(36) NOT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6032,
AVG_ROW_LENGTH = 106,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

DELIMITER $$

--
-- Create procedure `Proc_ImprotExcel`
--
CREATE PROCEDURE Proc_ImprotExcel (IN IntentUtterName varchar(255), IN Content text, IN UtterRes text, IN StoryName varchar(255))
SQL SECURITY INVOKER
BEGIN
  INSERT INTO intents (name, intent_uuid, created_at, updated_at)
    VALUES (IntentUtterName, UUID(), NOW(), NOW());
  SET @a = (SELECT
      LAST_INSERT_ID());
  INSERT INTO examples (content, intent_id, created_at, updated_at)
    SELECT
      Content,
      @a,
      NOW(),
      NOW();

  INSERT INTO utters (name, utter_uuid, created_at, updated_at)
    VALUES (IntentUtterName, UUID(), NOW(), NOW());
  SET @b = (SELECT
      LAST_INSERT_ID());
  INSERT INTO utterresponses (content, utter_id, type, created_at, updated_at)
    SELECT
      UtterRes,
      @b,
      1,
      NOW(),
      NOW();

  INSERT INTO stories (name, story_uuid, created_at, updated_at)
    VALUES (StoryName, UUID(), NOW(), NOW());
  SET @c = (SELECT
      LAST_INSERT_ID());

  INSERT INTO storysteps (story_id, intent_id, utter_id, `index`, created_at, update_at)
    VALUES (@c, @a, @b, 1, NOW(), NOW());
END
$$

DELIMITER ;

--
-- Create table `users`
--
CREATE TABLE users (
  id int(11) NOT NULL AUTO_INCREMENT,
  provider_id varchar(255) NOT NULL,
  provider_user_id varchar(255) NOT NULL,
  provider varchar(255) NOT NULL,
  name varchar(255) DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  teacher_code varchar(255) DEFAULT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create table `sequelizemeta`
--
CREATE TABLE sequelizemeta (
  name varchar(255) NOT NULL,
  PRIMARY KEY (name)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create index `name` on table `sequelizemeta`
--
ALTER TABLE sequelizemeta
ADD UNIQUE INDEX name (name);

--
-- Create table `questions`
--
CREATE TABLE questions (
  id int(11) NOT NULL AUTO_INCREMENT,
  question_uuid char(36) NOT NULL,
  content text NOT NULL,
  user_id int(11) NOT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create table `admins`
--
CREATE TABLE admins (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;